### ISSUE TITLE
data returned to promises always HTML, prefer JSON

### ISSUE THREAD

**Issue by wimrijnders** [johnculviner/jquery.fileDownload#105]
Hi there,

I use the following javascript for jquery fileDownload:

	$.fileDownload(action, {
		httpMethod: "POST",
		data: fields
	})
	// done() ignored, doesn't work anyway
	.fail(function (data) {
		// Expecting json, get HTML instead
		// Do some handling here with the expected data.
	});

On the server side, I check if a file is downloadable. If all is well, the cookie and other fields are filled in as usual. If there's an error, I send a json structure (also setting the http error code to 404 and setting a correct content type), containing an error message instead.

Thankfully, adding a data parameter to `fail()` works. However, even if the content type is set to a json type (eg. `application/json`), the data parameter still is a string with html tags. eg:

    "<pre style="word-wrap: break-word; white-space: pre-wrap;">{ "status": "ERROR", "error":"File'<filename>' not present, can not download" }</pre>"

To get around this, I currently send a `text/plain` message and convert to plain text locally, i.e.:

		var msg = $(data).text();

This is cumbersome, I'd much rather prefer to get json data directly.

**Comment by geudrik** [comment]
Even if not JSON, return the actual response object... Not having the option to do this really limits this library in practical use cases.

**Comment by johnculviner** [comment]
There is no response object nor way to have stuff from across without formatting (that <pre> is actually browser dependent). This is because this plugin uses a hidden <iframe>. <iframe>s are not AJAX so this just simply not possible. Depending on the browsers you need to support (and file sizes) you may be able to get away with this plugin that allows you to use AJAX and then save the file binary locally https://github.com/eligrey/FileSaver.js/
