### ISSUE TITLE
Sending JSON as POST data

### ISSUE THREAD

**Issue by radiodario** [johnculviner/jquery.fileDownload#13]
Hi there,

I'm writing a service that queries a server using pretty complex POST queries (elasticsearch style) that are sent as JSON. I've realised this plugin converts the POST data into a form that then it places on an iframe to begin the download. 

The kind of queries i'm making cannot easily be converted to key-value pairs without nesting. Is there a way i can pass JSON data?

Thanks

**Comment by jeff-h** [comment]
@niki4810 I know it's on the late side, being two years too late lol... but anyway, I made this work along the lines of https://github.com/johnculviner/jquery.fileDownload/issues/13#issuecomment-24195810 but instead of:

```js
          data: {query : myObj},
```

you need to convert your object into a JSON string first.

```js
          data: {query : JSON.stringify(myObj)},
```

This works for me and I'm not even using POST. The plugin appears to be smart enough to pass it via the URL query string.

**Comment by sumitshrm4** [comment]
I need to pass two param in data both are string. I am doing it in this way 

data : {url: '<%=XXX.Config.AppSettings.Settings["RESTServiceURL"].Value%>/DownloadFares', fareFilter: JSON.stringify(data1), ExtensionData:'""'}


But this is not working, how can i achieve this ?

**Comment by phx255** [comment]
Can't send as JSON parameter. Jquery fileDownload will build a form with the parameters (serialized). So change your backend code.
