### ISSUE TITLE
Catch status codes returned

### ISSUE THREAD

**Issue by ganna-shmatova** [johnculviner/jquery.fileDownload#62]
like Ajax or something similar.

**Comment by geudrik** [comment]
Yes. +1

The response object needs to be returned, not just html.

**Comment by johnculviner** [comment]
There is no response object nor way to have a response code. This is because this plugin uses a hidden iframe. iframes are not AJAX so this just simply not possible. Depending on the browsers you need to support (and file sizes) you may be able to get away with this plugin that allows you to use AJAX and then save the file binary locally https://github.com/eligrey/FileSaver.js/

**Comment by geudrik** [comment]
Any chance you can return the raw content then, instead of content wrapped in html tags? Currently, the only way to get the actual content is to load the returned html into a jQuery object, and `.innerHTML`

**Comment by johnculviner** [comment]
The way the browser decides to represent for example application/json in the iframe is VERY browser, browser version dependent. (Heck even plugins might effect this). I don't think you can reliably do this but I'd be happy to accept PRs if you go through the trouble to getting it to work reliably on a few browsers

**Comment by johnculviner** [comment]
Make a new issue about this specifically (not status codes) and I'd be happy to accept a PR
