### ISSUE TITLE
No callback after the file download

### ISSUE THREAD

**Issue by mspapant** [johnculviner/jquery.fileDownload#7]
The successCallback function is not called after the prompt for file save is displayed.
Check the example:

http://jsfiddle.net/B7nWs/

**Comment by jvzoggel** [comment]
After securing an MVC application with <httpCookies httpOnlyCookies="true" /> the plugin stopped working. Make sure you set the HttpOnly flag to false in the part where the cookies are created:
                response.AppendCookie(new HttpCookie(CookieName, "true") { Path = CookiePath, HttpOnly = false });

**Comment by jeff-h** [comment]
I had this issue too. Reading the above, I don't know what HTTPOnly is about, but I managed to fix my problem by adding the following response header, which I copied from the "PHP (with example file)" section of http://johnculviner.com/jquery-file-download-plugin-for-ajax-like-feature-rich-file-downloads/ :

`header('Cache-Control: max-age=60, must-revalidate');`

In other words, it was failing to fire any callbacks due to some cache header being there or not being there. A bit vague I know, but hopefully of use to someone :)

**Comment by bh81gh** [comment]
I managed to solve the problem by setting httpOnlyCookies="false" in web.config. Thanks for the help!!
